### PR TITLE
Fixed previous fixed error for tests

### PR DESCRIPTION
**Pull request by Pablo1990**
I commit this same fix, but don't know why it didn't go through (even though I pushed it)...

### CODE REVIEW

**Comment by giuliapaci** [comment]
Hi Pablo, 

I had made that change (adding a `_`)  previously to fix a problem which occurs now if you try running the 1-channel projection. This is because `calculate_projection` now gives two outputs so the `_` captures the "empty" one which is a None in the case of a single channel. 

To replicate the error (attached), I opened a stack in Napari and then tried running Plugins -> epitools -> Projection(selective plane)

If you look in the tests, inside `test_projection`, `test_calculate_projection` has the same `_` and that test passes. If you remove it, it fails. Not sure how to fix the linter without running again into this problem

Screenshot 2023-08-11 at 09 23 39

**Comment by Pablo1990** [comment]
Hi Giulia,

Thanks for checking! We might have to use two different functions then or maybe and if-else? What do you think it would be better?

**Comment by alessandrofelder** [comment]
Not sure it's much nicer, but you could use star-unpacking to handle both cases?
Something like (pseudocode for `main.py`):
```python
viewer = napari.current_viewer()
*projected_data = calculate_projections(...) # the preceding * gathers all outputs into a list however many there are
for i, projection in enumerate(projected_data):
		if projection is not None:
	        viewer.add_image(
	            data=projection,
	            name=f"Projection_ch{i}",
	            scale=image.scale,
	            translate=image.translate,
	            rotate=image.rotate,
	            plane=image.plane,
	            metadata=image.metadata,
	        )

**Comment by Pablo1990** [comment]
I don't know why it closed, I just reset the branch. Now, I've fixed the tests rather than touching the code. Tests are passing now.

**Review by giuliapaci — APPROVED** [review]
All looks good, I have tested with images and both projection (1 channel and 2 channel) work!

**Pull request merged**
